<?php
return [
    'defaultLimit' => 20,
    'adminEmail' => 'admin@example.com',
    'menu_list' => [
        ['name' => '主页', 'url' => '/index', 'icon' => 'glyphicon glyphicon-home'],
        ['name' => '账号管理', 'url' => '/role', 'icon' => '', 'item' => [
            ['name' => '表单', 'url' => '/role/add'],
            ['name' => '表格', 'url' => '/role/table'],
        ]],
        ['name' => '购书中心管理', 'url' => '/bookcenter', 'icon' => 'glyphicon glyphicon-align-center'],
        ['name' => '部门管理', 'url' => '/department', 'icon' => 'glyphicon glyphicon-menu-hamburger'],
        ['name' => '员工管理', 'url' => '/staff', 'icon' => 'glyphicon glyphicon-user'],
        ['name' => '书籍管理', 'url' => '/book', 'icon' => 'glyphicon glyphicon-book'],
        ['name' => '出版商管理', 'url' => '/publisher', 'icon' => 'glyphicon glyphicon-edit'],
        ['name' => '采购记录', 'url' => '/purchasing', 'icon' => 'glyphicon glyphicon-list-alt'],
        ['name' => '仓库管理', 'url' => '/warehouse', 'icon' => 'fa fa-truck'],
        ['name' => '销售记录', 'url' => '/sale', 'icon' => 'glyphicon glyphicon-list-alt'],
        ['name' => '工资管理', 'url' => '/wages', 'icon' => 'glyphicon glyphicon-yen'],
        ['name' => '报表', 'url' => '/charts', 'icon' => 'glyphicon glyphicon-stats', 'item' => [
            ['name' => '月利润报表', 'url' => '/charts/profit'],
            ['name' => '销售报表', 'url' => '/charts/sold'],
            ['name' => '工资报表', 'url' => '/charts/wages'],
            ['name' => '进货报表', 'url' => '/charts/purchase'],
            ['name' => '运营报表', 'url' => '/charts/operate'],
            ['name' => '仓库存储报表', 'url' => '/charts/warehouse'],
        ]],
    ],
    'department' => array(
        '行政部',
        '财务部',
        '质量管理部',
        '营销部',
        '运营部',
        '技术部',
        '维护部',
        '人力资源部',
        '客户服务部',
    ),
    'xyftRank' => [
        'one' => ['rank' => 1, 'rankDesc'=>'冠军'],
        'two' => ['rank'=>2, 'rankDesc'=>'亚军'],
        'three' => ['rank'=>3, 'rankDesc'=>'第三名'],
        'four'=> ['rank'=>4, 'rankDesc'=>'第四名'],
        'five'=> ['rank'=>5, 'rankDesc'=>'第五名'],
        'six'=> ['rank'=>6, 'rankDesc'=>'第六名'],
        'seven'=> ['rank'=>7, 'rankDesc'=>'第七名'],
        'eight'=> ['rank'=>8, 'rankDesc'=>'第八名'],
        'nine'=> ['rank'=>9, 'rankDesc'=>'第九名'],
        'ten'=> ['rank'=>10, 'rankDesc'=>'第十名']
    ],
];
